[package]
name = "mips"
version = "0.1.0"
authors = ["simon <simon@jotta.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mips"
path = "src/lib.rs"

[dependencies]
num-traits = "0.2.11"